name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Configuración de GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 3. Subida de archivos (tu sitio estático)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./   # carpeta donde está tu index.html

      # 4. Publicación en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
